---
title: "workflowr tutorial"
output: html_document
editor_optopns:
  chunck_output_type: console
---
##Set up

Load packages 
```{r pacakges}
library(ade4)
library(factoextra)
library(magrittr)

```

Load data
```{r}
##all accessions
all.acc <- read.csv("data/all.acc.csv")
dim(all.acc)

##for PC data
active.env <- na.omit(all.acc)
active.env <- active.env[,6:120]
##categorical that matches PC individuals 
active.env.cat <- na.omit(all.acc)
active.env.cat <- active.env.cat[,1:5]
```

PCA
```{r}
env.pc <- dudi.pca(active.env,
                    scannf = FALSE,   # Hide scree plot
                    nf = 10           # Number of components kept in the results
                   )
```

Scree plot
```{r}
fviz_eig(env.pc)
```

Biplot 
```{r}
##test for only founders
fviz_pca_biplot(env.pc,
                axes= c(1,2),
                col.var = "yellow", alpha=.8, # Variables color
                col.ind = "black",
                label = "var", # Individuals color,
                legend.title = "Races"
)

```
